# Generated by Django 2.2.4 on 2019-09-02 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('pubish_date', models.DateTimeField()),
                ('text', models.TextField(max_length=800)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
